/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoftwareRouteImport } from './routes/software'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as MyPageRouteImport } from './routes/my-page'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SoftwareIndexRouteImport } from './routes/software/index'

const SoftwareRoute = SoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPageRoute = MyPageRouteImport.update({
  id: '/my-page',
  path: '/my-page',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareIndexRoute = SoftwareIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SoftwareRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-page': typeof MyPageRoute
  '/publications': typeof PublicationsRoute
  '/software': typeof SoftwareRouteWithChildren
  '/software/': typeof SoftwareIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-page': typeof MyPageRoute
  '/publications': typeof PublicationsRoute
  '/software': typeof SoftwareIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-page': typeof MyPageRoute
  '/publications': typeof PublicationsRoute
  '/software': typeof SoftwareRouteWithChildren
  '/software/': typeof SoftwareIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/my-page' | '/publications' | '/software' | '/software/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/my-page' | '/publications' | '/software'
  id:
    | '__root__'
    | '/'
    | '/my-page'
    | '/publications'
    | '/software'
    | '/software/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyPageRoute: typeof MyPageRoute
  PublicationsRoute: typeof PublicationsRoute
  SoftwareRoute: typeof SoftwareRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/software': {
      id: '/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof SoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-page': {
      id: '/my-page'
      path: '/my-page'
      fullPath: '/my-page'
      preLoaderRoute: typeof MyPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software/': {
      id: '/software/'
      path: '/'
      fullPath: '/software/'
      preLoaderRoute: typeof SoftwareIndexRouteImport
      parentRoute: typeof SoftwareRoute
    }
  }
}

interface SoftwareRouteChildren {
  SoftwareIndexRoute: typeof SoftwareIndexRoute
}

const SoftwareRouteChildren: SoftwareRouteChildren = {
  SoftwareIndexRoute: SoftwareIndexRoute,
}

const SoftwareRouteWithChildren = SoftwareRoute._addFileChildren(
  SoftwareRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyPageRoute: MyPageRoute,
  PublicationsRoute: PublicationsRoute,
  SoftwareRoute: SoftwareRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
